---
title: "2016 - 2017 NBA Salary Predictions"
author: "Dylan Blechner, Steve Blechner"
date: "January 10, 2017"
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br><br>

### HOW I PREDICT NBA SALARIES
<br><br>

(Explanation here)
<br><br>
<br><br>

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(broom)
library(stargazer)
library(DT)
```

```{r echo=FALSE}
AllPosmodel.reduced3  <- readRDS("AllPosmodel_reduced3.rds")
```

### MULTIPLE LINEAR REGRESSION OF ALL FIVE NBA POSITIONS
<br>

```{r, echo=FALSE, results='asis'}
AllPosmodel.reduced3  %>%
  stargazer(type="html", 
            single.row = TRUE,
            summary=FALSE)
```
<br><br>
<br><br>


### PREDICTIONS OF ALL FIVE NBA POSITIONS
<br>
```{r, echo=FALSE, results='asis'}
Predicted.File <- "AllPos_FITvsACTUAL.csv"
Predicted.File %>%
  read.csv(check.names = FALSE, stringsAsFactors=FALSE) %>%
  tbl_df() %>%
  select(-lwr,-upr,-No.,-Salary,-Lg,-Pos.y,-Year) %>%
  arrange(desc(fit)) %>%
  datatable(rownames = FALSE, class="nowrap", extensions = 'FixedColumns',
            options = list(
              dom = 'tp',
              scrollX = TRUE,
              fixedColumns = list(leftColumns = 3)
            )) %>% 
  formatCurrency(1:2) %>% formatRound('Ht', 3)


```

<br>
<br>
